### PR TITLE
Modified QtControls to compile using Qwt 6.3.0

### PR DESCRIPTION
**Pull request by AbdallaDalleh**
Make complained with undefined reference to class QwtThermoMarker, with Qwt 6.3.0 this was excluded from the build (from caQtDM_QtControls.pro #210) v4.5.0 compiles with Qwt 6.3.0

### CODE REVIEW

**Comment by AbdallaDalleh** [comment]
Used qmake-qt5 to build for Qt5 under RHEL 9+ systems

On Rocky Linux 9.7, qmake defaults to Qt6 but it has qmake-qt5, qmake-qt5 also exists in 8.10 so this should not break builds.

**Comment by HelgeBrands** [comment]
Hi AbdallaDalleh,
thanks for your work on caQtDM. The problem is that there are multiple things to take into account. Since we are at the moments backwards compatible down to Qt 4.8 and up to Qt 6.10 your changes with qmake-qt5 are not working. Even this is not taking into account that the script has to work on Mac too. qmake-qt5 is an invention from Linux systems where are multiple Qt Versions, but there is on some distributions a thing that called qtswitcher!
The other change would be ok, but in the near future I have to skip the old QWT version. That was needed for Qt 4.6.2!
It takes me some time to remove old things, sorry.
Best regards
    Helge

**Comment by AbdallaDalleh** [comment]
I agree with you, as I never though caQtDM is backwards compatible to Qt 4.8, my original intention is to be able to select Qt version in case you have multiple version, Qt5 and Qt6 on a Rocky 9 system. What about adding a new variable in `caQtDM_Env`, say for example `QMAKE` that defaults to `qmake`?

**Comment by AbdallaDalleh** [comment]
I just noticed the issue is closed. Not including `contains(QWT_VER_MIN, 3)` breaks builds with Qwt 6.3.0, do you want me to modify the PR to remove `qmake` update? Also, what do mean by " old QWT version"? The latest Qwt tag is 6.3.0. Thanks!

**Comment by HelgeBrands** [comment]
There are some other thoughts about qmake. The future of Qt building application will be cmake.

There is no breaking problems with QWT. The problem was an API change between QWT 6.0 and 6.1. All higher versions (6.2 and 6.3) have the same and the QWT_VER_MIN is only a simple switch between these two APIs.

**Comment by AbdallaDalleh** [comment]
What I meant is to keep `contains(QWT_VER_MIN, 3)` until you remove the old `qwt` version so the `qmake` is still comparing for minor version 1, 2, or 3 because without it it will not compile the QWT Thermo marker for `qwt` 6.3.0 and `undefined reference` errors pop out.

**Comment by HelgeBrands** [comment]
I added now a better fix for your problem that covers your problem and some more.
